version: '3'
services:
  siseng:
    build: .
    environment:
      TZ: "America/Fortaleza"
    volumes:
    - ~/.m2:/home/paulo/.m2
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    ports:
    - 9092:9092
    command: mvn clean spring-boot:run
